/**
 * Noor brand palette — derived from the official NOOR logo (UX-1, ADR
 * 0013). Anchors were independently pixel-sampled from the approved
 * artwork (apps/web/public/brand/source/noor-logo-original.jpeg) and
 * cross-checked against the logo's own supplied reference values before
 * being finalized — see docs/design/noor-color-system.md for the
 * sampling method and the exact anchor-vs-sample comparison. Every step
 * below is contrast-checked against WCAG 2.2 AA; see
 * docs/design/noor-accessibility-review.md.
 *
 * Deep Navy (#032855) → structural text ("ink"). Clinical Blue (#045092)
 * → primary interaction. Primary Teal (#078A88) → navigation/focus
 * accent. Emerald (#09B993) → restrained success/highlight emphasis.
 * Clinical semantic meaning (danger/warning/critical) intentionally does
 * NOT use these brand hues — see semanticStates below and ADR 0013 §4.3.
 */

/** Full 50–950 ramps for the four brand-defining hues, generated by
 * blending each anchor toward white (light steps) or near-black (dark
 * steps) in linear RGB — not raw HSL lightness, which produced
 * over-saturated "neon" mid-tones for these highly saturated teal/
 * emerald anchors. Anchor sits at 500. Used for gradient endpoints,
 * brand-expression surfaces, and the design-system swatch page — feature
 * UI should prefer the semantic tokens (primary/accent/ink/...) below,
 * not these raw scales, so a future brand adjustment only touches one
 * place. */
export const brandNavy = {
  50: "#F0F2F5", 100: "#E1E5EB", 200: "#BDC7D3", 300: "#95A5B8", 400: "#59718F",
  500: "#032855", 600: "#042349", 700: "#061F3D", 800: "#071A32", 900: "#081627", 950: "#09131F",
} as const;

export const brandBlue = {
  50: "#F0F4F8", 100: "#E1EAF2", 200: "#BED2E3", 300: "#96B6D1", 400: "#598CB7",
  500: "#045092", 600: "#05447B", 700: "#063864", 800: "#072E4F", 900: "#08233B", 950: "#091B2C",
} as const;

export const brandTeal = {
  50: "#F0F8F8", 100: "#E1F1F1", 200: "#BFE1E0", 300: "#97CECD", 400: "#5BB2B0",
  500: "#078A88", 600: "#087473", 700: "#085D5E", 800: "#094A4B", 900: "#093638", 950: "#09272A",
} as const;

export const brandEmerald = {
  50: "#F0FBF9", 100: "#E1F7F2", 200: "#BFEDE3", 300: "#98E2D2", 400: "#5DD1B8",
  500: "#09B993", 600: "#099A7C", 700: "#097B65", 800: "#0A6050", 900: "#0A453B", 950: "#0A302C",
} as const;

/** Supporting tones only — a few concrete steps, not a full forced
 * ramp (mission guidance: don't generate scale steps with no real use).
 * `cyan300` is pinned to the logo's own supplied soft-cyan reference
 * (#B6DAE0) rather than the computed ramp, to keep that exact anchor
 * available verbatim for the one or two places it's actually used (the
 * auth support panel, brand documentation swatches). */
export const brandCyan = {
  50: "#F3F8F9", 100: "#E8F1F2", 200: "#CDE0E3", 300: "#B6DAE0", 400: "#80B1B9", 600: "#35737D",
} as const;

export const brandSlate = {
  50: "#F6F9FA", 100: "#EEF3F5", 300: "#C2D6DA", 500: "#6E9DA8", 700: "#4A6A72",
} as const;

/** The one official brand gradient (ADR 0013) — blue → teal → emerald,
 * matching the hue progression of the "N" symbol itself. Used sparingly:
 * a thin accent line under the primary logo lockup, the login hero
 * panel, and small "active AI pipeline" accents — never as a button or
 * card default (see docs/design/noor-color-system.md §Gradient usage). */
export const brandGradient = "linear-gradient(135deg, #045092 0%, #078A88 52%, #09B993 100%)";

/**
 * Semantic slots every component actually renders through — the layer
 * that stays stable even if the underlying brand hue is revisited later.
 * `primary` (Clinical Blue) drives buttons/CTAs/links; `accent` (Primary
 * Teal) drives navigation-active state and the focus ring, matching the
 * logo's own "N" gradient direction (blue interaction → teal wayfinding).
 */
export const brandColors = {
  primary: brandBlue[500],
  primaryActive: brandBlue[600],
  primarySoft: brandBlue[100],

  accent: brandTeal[500],
  accentActive: brandTeal[700],
  accentSoft: brandTeal[100],

  ink: brandNavy[500],
  body: "#0F3A61",
  muted: brandNavy[400],
  mutedSoft: brandNavy[300],

  canvas: "#FFFFFF",
  surfaceSoft: brandBlue[50],
  surfaceStrong: brandNavy[100],

  border: "#DCE2E9",
  borderStrong: "#B9C6D2",

  onPrimary: "#FFFFFF",
  onAccent: "#FFFFFF",
} as const;

/**
 * Dark-mode mirror of brandColors. Same relationships (ink stays the
 * darkest text tone, canvas stays the page floor) inverted for a dark
 * surface — kept alongside the light values so both are reviewed together
 * instead of dark mode being an afterthought.
 */
export const brandColorsDark = {
  primary: brandBlue[400],
  primaryActive: brandBlue[300],
  primarySoft: brandBlue[900],

  accent: brandTeal[400],
  accentActive: brandTeal[300],
  accentSoft: brandTeal[900],

  ink: "#EAF1F0",
  body: "#C7D3DE",
  muted: "#8FA4B3",
  mutedSoft: "#5C7186",

  canvas: "#0B141F",
  surfaceSoft: "#111C29",
  surfaceStrong: "#182633",

  border: "#25384A",
  borderStrong: "#3C5570",

  onPrimary: brandNavy[950],
  onAccent: brandNavy[950],
} as const;

export type SemanticStateKey =
  | "evidenceSufficient"
  | "evidencePartial"
  | "evidenceInsufficient"
  | "evidenceConflicting"
  | "verified"
  | "humanApproved"
  | "aiGenerated"
  | "warning"
  | "critical"
  | "informational"
  | "inactive"
  | "superseded"
  | "withdrawn"
  | "processing"
  | "underReview"
  | "failed"
  | "queued"
  | "retryScheduled"
  | "ocrRequired"
  | "reprocessingRequired"
  | "deadLettered";

export interface SemanticStateToken {
  label: string;
  /** Screen-reader description — never rely on color/icon alone. */
  accessibleDescription: string;
  helperText?: string;
  icon:
    | "check-circle"
    | "alert-triangle"
    | "alert-octagon"
    | "shuffle"
    | "user-check"
    | "sparkles"
    | "info"
    | "ban"
    | "archive"
    | "loader"
    | "eye"
    | "x-circle"
    | "circle-dashed"
    | "clock"
    | "rotate-cw"
    | "rotate-ccw"
    | "scan-line";
  fg: string;
  bg: string;
  border: string;
  fgDark: string;
  bgDark: string;
  borderDark: string;
}

/**
 * Every clinical/system status Noor surfaces. Color is never the only
 * signal — each state carries a label, an icon recommendation, and an
 * accessible description a screen reader announces regardless of color
 * perception (Security/Clinical-Safety requirement: "do not use color
 * alone to convey clinical meaning").
 *
 * Brand alignment (UX-1, ADR 0013 §4.3): positive/neutral states
 * (success, informational, processing) now use the brand's own emerald/
 * blue hues, reinforcing identity with zero safety cost. Danger/warning/
 * critical deliberately keep their pre-existing, universally-recognized
 * red/amber — the brand palette must never blur a safety signal.
 */
export const semanticStates: Record<SemanticStateKey, SemanticStateToken> = {
  evidenceSufficient: {
    label: "Evidence sufficient",
    accessibleDescription: "The guideline evidence fully supports this answer.",
    icon: "check-circle",
    fg: brandEmerald[700], bg: brandEmerald[50], border: brandEmerald[300],
    fgDark: "#5FE0BC", bgDark: "#0E2A22", borderDark: "#1E4A3B",
  },
  evidencePartial: {
    label: "Evidence partial",
    accessibleDescription: "Some, but not all, of this answer is directly supported by cited evidence.",
    helperText: "Review flagged statements before relying on this answer.",
    icon: "alert-triangle",
    fg: "#7A4E00", bg: "#FCF0D8", border: "#F0D28C",
    fgDark: "#F0C56A", bgDark: "#2E2408", borderDark: "#4D3D10",
  },
  evidenceInsufficient: {
    label: "Evidence insufficient",
    accessibleDescription: "There is not enough approved guideline evidence to answer this safely. Noor has declined to generate a recommendation.",
    helperText: "This is a fail-closed safety state, not an error.",
    icon: "ban",
    fg: "#8A2C1D", bg: "#FBE4DE", border: "#EFB3A4",
    fgDark: "#F1A088", bgDark: "#331A12", borderDark: "#54291B",
  },
  evidenceConflicting: {
    label: "Evidence conflicting",
    accessibleDescription: "Approved sources disagree with one another on this point.",
    helperText: "Requires clinician judgment and, where relevant, reviewer escalation.",
    icon: "shuffle",
    fg: "#5B2A86", bg: "#EEE2F7", border: "#D3B4E8",
    fgDark: "#C99EE8", bgDark: "#241130", borderDark: "#3E2050",
  },
  verified: {
    label: "Verified",
    accessibleDescription: "This record has been checked and confirmed accurate.",
    icon: "check-circle",
    fg: brandEmerald[700], bg: brandEmerald[50], border: brandEmerald[300],
    fgDark: "#5FE0BC", bgDark: "#0E2A22", borderDark: "#1E4A3B",
  },
  humanApproved: {
    label: "Human approved",
    accessibleDescription: "A named clinical reviewer approved this content.",
    icon: "user-check",
    fg: brandEmerald[800], bg: brandEmerald[100], border: brandEmerald[400],
    fgDark: "#78D3A2", bgDark: "#0C2A1B", borderDark: "#1B472C",
  },
  aiGenerated: {
    label: "AI-generated",
    accessibleDescription: "This content was generated by Noor's AI pipeline and has not yet received human clinical approval.",
    helperText: "Always distinguished from human-approved content — never shown without this label.",
    icon: "sparkles",
    fg: "#3A3B99", bg: "#E6E6FA", border: "#C2C3EF",
    fgDark: "#B4B5F2", bgDark: "#1E1F4D", borderDark: "#33348A",
  },
  warning: {
    label: "Warning",
    accessibleDescription: "A safety-relevant condition needs your attention.",
    icon: "alert-triangle",
    fg: "#7A4E00", bg: "#FCF0D8", border: "#F0D28C",
    fgDark: "#F0C56A", bgDark: "#2E2408", borderDark: "#4D3D10",
  },
  critical: {
    label: "Critical",
    accessibleDescription: "A critical safety issue requires immediate action.",
    icon: "alert-octagon",
    fg: "#7A1F14", bg: "#FBDCD5", border: "#EDA294",
    fgDark: "#F29684", bgDark: "#331410", borderDark: "#5C241A",
  },
  informational: {
    label: "Informational",
    accessibleDescription: "For your information — no action required.",
    icon: "info",
    fg: brandBlue[700], bg: brandBlue[50], border: brandBlue[300],
    fgDark: "#9AC1F2", bgDark: "#12233F", borderDark: "#1F3C63",
  },
  inactive: {
    label: "Inactive",
    accessibleDescription: "This item is not currently active.",
    icon: "circle-dashed",
    fg: brandNavy[400], bg: brandNavy[50], border: brandNavy[200],
    fgDark: "#9FACAB", bgDark: "#1C2424", borderDark: "#333F3E",
  },
  superseded: {
    label: "Superseded",
    accessibleDescription: "A newer version of this guideline replaces this one.",
    icon: "archive",
    fg: "#374863", bg: "#E6EBF4", border: "#BCC9DE",
    fgDark: "#A9B9D6", bgDark: "#1B2333", borderDark: "#2F3C55",
  },
  withdrawn: {
    label: "Withdrawn",
    accessibleDescription: "This guideline has been withdrawn and must not be used.",
    helperText: "Withdrawn content is retained for audit only — never shown as retrievable evidence.",
    icon: "x-circle",
    fg: "#5C231A", bg: "#F2DFDA", border: "#DCAB9D",
    fgDark: "#D69C8B", bgDark: "#2B160F", borderDark: "#492A1F",
  },
  processing: {
    label: "Processing",
    accessibleDescription: "This is currently being processed.",
    icon: "loader",
    fg: brandBlue[700], bg: brandBlue[50], border: brandBlue[300],
    fgDark: "#9AC1F2", bgDark: "#12233F", borderDark: "#1F3C63",
  },
  underReview: {
    label: "Under review",
    accessibleDescription: "A clinical reviewer is currently examining this item.",
    icon: "eye",
    fg: brandBlue[700], bg: brandBlue[50], border: brandBlue[300],
    fgDark: "#9AC1F2", bgDark: "#12233F", borderDark: "#1F3C63",
  },
  failed: {
    label: "Failed",
    accessibleDescription: "This process did not complete successfully.",
    icon: "alert-octagon",
    fg: "#7A1F14", bg: "#FBDCD5", border: "#EDA294",
    fgDark: "#F29684", bgDark: "#331410", borderDark: "#5C241A",
  },
  queued: {
    label: "Queued",
    accessibleDescription: "This is waiting in line to be processed. Nothing is wrong.",
    icon: "clock",
    fg: brandSlate[700], bg: brandSlate[50], border: brandSlate[300],
    fgDark: "#A9C2C9", bgDark: "#182428", borderDark: "#2C4147",
  },
  retryScheduled: {
    label: "Retry scheduled",
    accessibleDescription: "This attempt failed and has been automatically scheduled to run again.",
    helperText: "No action is needed unless this keeps recurring.",
    icon: "rotate-cw",
    fg: "#8A4B00", bg: "#FDEEDD", border: "#F2C594",
    fgDark: "#F0B26A", bgDark: "#2E2008", borderDark: "#4D3610",
  },
  ocrRequired: {
    label: "OCR required",
    accessibleDescription: "A reviewer has determined this page needs optical character recognition before it can be used.",
    icon: "scan-line",
    fg: brandTeal[800], bg: brandTeal[50], border: brandTeal[300],
    fgDark: "#7AD6D4", bgDark: "#0E2A2A", borderDark: "#1E4A49",
  },
  reprocessingRequired: {
    label: "Reprocessing required",
    accessibleDescription: "A reviewer has determined this result is not usable as-is and must be redone.",
    helperText: "Distinct from a retry: this was a deliberate human technical decision, not an automatic retry.",
    icon: "rotate-ccw",
    fg: "#6B2F6B", bg: "#F5E6F0", border: "#E0B8D9",
    fgDark: "#E0A8DA", bgDark: "#2E1830", borderDark: "#4D2C4E",
  },
  deadLettered: {
    label: "Dead-lettered",
    accessibleDescription: "This job exhausted its retry attempts and requires manual intervention.",
    helperText: "More severe than a single failure — automatic retries have been exhausted.",
    icon: "ban",
    fg: "#43140A", bg: "#EFDAD3", border: "#D89985",
    fgDark: "#E0A088", bgDark: "#2E140C", borderDark: "#4D261A",
  },
};
