/**
 * Noor brand palette — Deep Teal / Emerald direction (ADR 0005).
 * Starting values, not immutable brand law. Contrast-checked against WCAG
 * 2.1 AA in docs/design-system/ACCESSIBILITY.md; re-verify here if changed.
 */
export const brandColors = {
  primary: "#087F73",
  primaryActive: "#06685F",
  primarySoft: "#DDF4F0",

  ink: "#172121",
  body: "#344342",
  muted: "#667574",
  mutedSoft: "#8A9796",

  canvas: "#FFFFFF",
  surfaceSoft: "#F6F8F8",
  surfaceStrong: "#EDF2F1",

  border: "#D9E1E1",
  borderStrong: "#B9C6C4",

  onPrimary: "#FFFFFF",
} as const;

/**
 * Dark-mode mirror of brandColors. Same relationships (ink stays the
 * darkest text tone, canvas stays the page floor) inverted for a dark
 * surface — kept alongside the light values so both are reviewed together
 * instead of dark mode being an afterthought.
 */
export const brandColorsDark = {
  primary: "#1FA99A",
  primaryActive: "#3FC2B2",
  primarySoft: "#0E2E2A",

  ink: "#EAF1F0",
  body: "#C3D0CE",
  muted: "#8FA09E",
  mutedSoft: "#6B7A78",

  canvas: "#101717",
  surfaceSoft: "#161F1F",
  surfaceStrong: "#1E2A29",

  border: "#2A3736",
  borderStrong: "#3C4C4A",

  onPrimary: "#08201C",
} as const;

export type SemanticStateKey =
  | "evidenceSufficient"
  | "evidencePartial"
  | "evidenceInsufficient"
  | "evidenceConflicting"
  | "verified"
  | "humanApproved"
  | "aiGenerated"
  | "warning"
  | "critical"
  | "informational"
  | "inactive"
  | "superseded"
  | "withdrawn"
  | "processing"
  | "underReview"
  | "failed";

export interface SemanticStateToken {
  label: string;
  /** Screen-reader description — never rely on color/icon alone. */
  accessibleDescription: string;
  helperText?: string;
  icon: "check-circle" | "alert-triangle" | "alert-octagon" | "shuffle" | "user-check" | "sparkles" | "info" | "ban" | "archive" | "loader" | "eye" | "x-circle" | "circle-dashed";
  fg: string;
  bg: string;
  border: string;
  fgDark: string;
  bgDark: string;
  borderDark: string;
}

/**
 * Every clinical/system status Noor surfaces. Color is never the only
 * signal — each state carries a label, an icon recommendation, and an
 * accessible description a screen reader announces regardless of color
 * perception (Security/Clinical-Safety requirement: "do not use color
 * alone to convey clinical meaning").
 */
export const semanticStates: Record<SemanticStateKey, SemanticStateToken> = {
  evidenceSufficient: {
    label: "Evidence sufficient",
    accessibleDescription: "The guideline evidence fully supports this answer.",
    icon: "check-circle",
    fg: "#0F5132", bg: "#DFF3E8", border: "#A6DFC3",
    fgDark: "#7FDDA8", bgDark: "#0E2A1C", borderDark: "#1E4A31",
  },
  evidencePartial: {
    label: "Evidence partial",
    accessibleDescription: "Some, but not all, of this answer is directly supported by cited evidence.",
    helperText: "Review flagged statements before relying on this answer.",
    icon: "alert-triangle",
    fg: "#7A4E00", bg: "#FCF0D8", border: "#F0D28C",
    fgDark: "#F0C56A", bgDark: "#2E2408", borderDark: "#4D3D10",
  },
  evidenceInsufficient: {
    label: "Evidence insufficient",
    accessibleDescription: "There is not enough approved guideline evidence to answer this safely. Noor has declined to generate a recommendation.",
    helperText: "This is a fail-closed safety state, not an error.",
    icon: "ban",
    fg: "#8A2C1D", bg: "#FBE4DE", border: "#EFB3A4",
    fgDark: "#F1A088", bgDark: "#331A12", borderDark: "#54291B",
  },
  evidenceConflicting: {
    label: "Evidence conflicting",
    accessibleDescription: "Approved sources disagree with one another on this point.",
    helperText: "Requires clinician judgment and, where relevant, reviewer escalation.",
    icon: "shuffle",
    fg: "#5B2A86", bg: "#EEE2F7", border: "#D3B4E8",
    fgDark: "#C99EE8", bgDark: "#241130", borderDark: "#3E2050",
  },
  verified: {
    label: "Verified",
    accessibleDescription: "This record has been checked and confirmed accurate.",
    icon: "check-circle",
    fg: "#0F5132", bg: "#DFF3E8", border: "#A6DFC3",
    fgDark: "#7FDDA8", bgDark: "#0E2A1C", borderDark: "#1E4A31",
  },
  humanApproved: {
    label: "Human approved",
    accessibleDescription: "A named clinical reviewer approved this content.",
    icon: "user-check",
    fg: "#0B4A2E", bg: "#DCF1E6", border: "#9FDABC",
    fgDark: "#78D3A2", bgDark: "#0C2A1B", borderDark: "#1B472C",
  },
  aiGenerated: {
    label: "AI-generated",
    accessibleDescription: "This content was generated by Noor's AI pipeline and has not yet received human clinical approval.",
    helperText: "Always distinguished from human-approved content — never shown without this label.",
    icon: "sparkles",
    fg: "#3A3B99", bg: "#E6E6FA", border: "#C2C3EF",
    fgDark: "#B4B5F2", bgDark: "#1E1F4D", borderDark: "#33348A",
  },
  warning: {
    label: "Warning",
    accessibleDescription: "A safety-relevant condition needs your attention.",
    icon: "alert-triangle",
    fg: "#7A4E00", bg: "#FCF0D8", border: "#F0D28C",
    fgDark: "#F0C56A", bgDark: "#2E2408", borderDark: "#4D3D10",
  },
  critical: {
    label: "Critical",
    accessibleDescription: "A critical safety issue requires immediate action.",
    icon: "alert-octagon",
    fg: "#7A1F14", bg: "#FBDCD5", border: "#EDA294",
    fgDark: "#F29684", bgDark: "#331410", borderDark: "#5C241A",
  },
  informational: {
    label: "Informational",
    accessibleDescription: "For your information — no action required.",
    icon: "info",
    fg: "#1F4B8A", bg: "#DCE9FB", border: "#A9C8F0",
    fgDark: "#9AC1F2", bgDark: "#12233F", borderDark: "#1F3C63",
  },
  inactive: {
    label: "Inactive",
    accessibleDescription: "This item is not currently active.",
    icon: "circle-dashed",
    fg: "#4A5555", bg: "#EDF1F1", border: "#CBD5D4",
    fgDark: "#9FACAB", bgDark: "#1C2424", borderDark: "#333F3E",
  },
  superseded: {
    label: "Superseded",
    accessibleDescription: "A newer version of this guideline replaces this one.",
    icon: "archive",
    fg: "#374863", bg: "#E6EBF4", border: "#BCC9DE",
    fgDark: "#A9B9D6", bgDark: "#1B2333", borderDark: "#2F3C55",
  },
  withdrawn: {
    label: "Withdrawn",
    accessibleDescription: "This guideline has been withdrawn and must not be used.",
    helperText: "Withdrawn content is retained for audit only — never shown as retrievable evidence.",
    icon: "x-circle",
    fg: "#5C231A", bg: "#F2DFDA", border: "#DCAB9D",
    fgDark: "#D69C8B", bgDark: "#2B160F", borderDark: "#492A1F",
  },
  processing: {
    label: "Processing",
    accessibleDescription: "This is currently being processed.",
    icon: "loader",
    fg: "#1F4B8A", bg: "#DCE9FB", border: "#A9C8F0",
    fgDark: "#9AC1F2", bgDark: "#12233F", borderDark: "#1F3C63",
  },
  underReview: {
    label: "Under review",
    accessibleDescription: "A clinical reviewer is currently examining this item.",
    icon: "eye",
    fg: "#1F4B8A", bg: "#DCE9FB", border: "#A9C8F0",
    fgDark: "#9AC1F2", bgDark: "#12233F", borderDark: "#1F3C63",
  },
  failed: {
    label: "Failed",
    accessibleDescription: "This process did not complete successfully.",
    icon: "alert-octagon",
    fg: "#7A1F14", bg: "#FBDCD5", border: "#EDA294",
    fgDark: "#F29684", bgDark: "#331410", borderDark: "#5C241A",
  },
};
